default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/<%= ENV["RAILS_SYSTEM_TEST"] == "1" ? "system_test" : "test" %>.sqlite3

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_PATH", "storage/production.sqlite3") %>

